// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: zzzz-customer-job.proto

package customer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	job "github.com/SolmateDev/go-client/proto/job"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zzzz_customer_job_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zzzz_customer_job_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_zzzz_customer_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// optional; if omitted, all jobs are returned
	Status job.Status `protobuf:"varint,1,opt,name=status,proto3,enum=job.Status" json:"status,omitempty"`
	// optional
	Start int64 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	// optional
	Finish int64 `protobuf:"varint,3,opt,name=finish,proto3" json:"finish,omitempty"`
}

func (x *JobListRequest) Reset() {
	*x = JobListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zzzz_customer_job_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListRequest) ProtoMessage() {}

func (x *JobListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zzzz_customer_job_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobListRequest.ProtoReflect.Descriptor instead.
func (*JobListRequest) Descriptor() ([]byte, []int) {
	return file_zzzz_customer_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobListRequest) GetStatus() job.Status {
	if x != nil {
		return x.Status
	}
	return job.Status(0)
}

func (x *JobListRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *JobListRequest) GetFinish() int64 {
	if x != nil {
		return x.Finish
	}
	return 0
}

type JobListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*job.Job `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *JobListResponse) Reset() {
	*x = JobListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zzzz_customer_job_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListResponse) ProtoMessage() {}

func (x *JobListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zzzz_customer_job_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobListResponse.ProtoReflect.Descriptor instead.
func (*JobListResponse) Descriptor() ([]byte, []int) {
	return file_zzzz_customer_job_proto_rawDescGZIP(), []int{2}
}

func (x *JobListResponse) GetList() []*job.Job {
	if x != nil {
		return x.List
	}
	return nil
}

var File_zzzz_customer_job_proto protoreflect.FileDescriptor

var file_zzzz_customer_job_proto_rawDesc = []byte{
	0x0a, 0x17, 0x7a, 0x7a, 0x7a, 0x7a, 0x2d, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2d,
	0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x1a, 0x09, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29,
	0x0a, 0x10, 0x4a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x0e, 0x4a, 0x6f, 0x62,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6a, 0x6f,
	0x62, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x22, 0x2f,
	0x0a, 0x0f, 0x4a, 0x6f, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32,
	0x7e, 0x0a, 0x03, 0x4a, 0x6f, 0x62, 0x12, 0x33, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x4a,
	0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x08, 0x2e, 0x6a, 0x6f, 0x62, 0x2e, 0x4a, 0x6f, 0x62, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x4d, 0x79, 0x4a, 0x6f, 0x62, 0x73, 0x12, 0x18, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x65, 0x72, 0x2e, 0x4a, 0x6f, 0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x2e, 0x4a, 0x6f,
	0x62, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x21, 0x5a, 0x1f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x70, 0x61, 0x64, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x66, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zzzz_customer_job_proto_rawDescOnce sync.Once
	file_zzzz_customer_job_proto_rawDescData = file_zzzz_customer_job_proto_rawDesc
)

func file_zzzz_customer_job_proto_rawDescGZIP() []byte {
	file_zzzz_customer_job_proto_rawDescOnce.Do(func() {
		file_zzzz_customer_job_proto_rawDescData = protoimpl.X.CompressGZIP(file_zzzz_customer_job_proto_rawDescData)
	})
	return file_zzzz_customer_job_proto_rawDescData
}

var file_zzzz_customer_job_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_zzzz_customer_job_proto_goTypes = []interface{}{
	(*JobStatusRequest)(nil), // 0: customer.JobStatusRequest
	(*JobListRequest)(nil),   // 1: customer.JobListRequest
	(*JobListResponse)(nil),  // 2: customer.JobListResponse
	(job.Status)(0),          // 3: job.Status
	(*job.Job)(nil),          // 4: job.Job
}
var file_zzzz_customer_job_proto_depIdxs = []int32{
	3, // 0: customer.JobListRequest.status:type_name -> job.Status
	4, // 1: customer.JobListResponse.list:type_name -> job.Job
	0, // 2: customer.Job.GetStatus:input_type -> customer.JobStatusRequest
	1, // 3: customer.Job.GetMyJobs:input_type -> customer.JobListRequest
	4, // 4: customer.Job.GetStatus:output_type -> job.Job
	2, // 5: customer.Job.GetMyJobs:output_type -> customer.JobListResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_zzzz_customer_job_proto_init() }
func file_zzzz_customer_job_proto_init() {
	if File_zzzz_customer_job_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zzzz_customer_job_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zzzz_customer_job_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_zzzz_customer_job_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zzzz_customer_job_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zzzz_customer_job_proto_goTypes,
		DependencyIndexes: file_zzzz_customer_job_proto_depIdxs,
		MessageInfos:      file_zzzz_customer_job_proto_msgTypes,
	}.Build()
	File_zzzz_customer_job_proto = out.File
	file_zzzz_customer_job_proto_rawDesc = nil
	file_zzzz_customer_job_proto_goTypes = nil
	file_zzzz_customer_job_proto_depIdxs = nil
}
